grammar PGN    

game <- tag_pairs:tag_pairs [\n]? movetext:movetext
tag_pairs <- tag_pair* %make_tag_pairs
tag_pair <- "[" key " \"" value "\"]" dlm %make_tag_pair
key <- [A-Za-z]+
value <- [^\"]*

movetext <- move* %make_movetext
move <- move_number dlm white:san dlm wcomment:comment? dlm black:san dlm bcomment:comment? dlm
move_number <- [0-9]+ "." 
san <- [KQRNBP]? [a-h] [1-8]
comment <- "{" [^\}]* "}" %make_comment
dlm <- [\s]?
