grammar PGN    

root <- tag_pairs:tag_pair* newline? movetext:move_text*
tag_pair <- "[" key " \"" value "\"]" newline?
key <- [A-Za-z]+
value <- [^\"]*
newline <- [\n]?

move_text <- turn_no:turn_number delim white:turn delim black:turn delim?
turn_number <- [0-9]+ "." 
turn <- move tags?
move <- [KQRNBP]? [a-h] [1-8]   
tags <- anno_tag?
anno_tag <- delim? "{" annotation:annotation "}"
annotation <- [^}]*
delim <- [\s]?
